// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAChoz8kv1RZ8ybh1XLOZySCQYs9w0Mxn0',
    appId: '1:925784497699:web:56db3b6c4122de07241b96',
    messagingSenderId: '925784497699',
    projectId: 'sleep-assistant-2a5a3',
    authDomain: 'sleep-assistant-2a5a3.firebaseapp.com',
    storageBucket: 'sleep-assistant-2a5a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC07KdPXC7nusOiPWac9FZkn90bs5RJEVw',
    appId: '1:925784497699:android:89940cad2203661e241b96',
    messagingSenderId: '925784497699',
    projectId: 'sleep-assistant-2a5a3',
    storageBucket: 'sleep-assistant-2a5a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBId8CcNhnk-RaYCgQOJH7TZsqQj59uFFo',
    appId: '1:925784497699:ios:fc02fa8331ce0265241b96',
    messagingSenderId: '925784497699',
    projectId: 'sleep-assistant-2a5a3',
    storageBucket: 'sleep-assistant-2a5a3.firebasestorage.app',
    iosBundleId: 'com.example.sleepAssistantFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBId8CcNhnk-RaYCgQOJH7TZsqQj59uFFo',
    appId: '1:925784497699:ios:fc02fa8331ce0265241b96',
    messagingSenderId: '925784497699',
    projectId: 'sleep-assistant-2a5a3',
    storageBucket: 'sleep-assistant-2a5a3.firebasestorage.app',
    iosBundleId: 'com.example.sleepAssistantFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAChoz8kv1RZ8ybh1XLOZySCQYs9w0Mxn0',
    appId: '1:925784497699:web:56db3b6c4122de07241b96',
    messagingSenderId: '925784497699',
    projectId: 'sleep-assistant-2a5a3',
    authDomain: 'sleep-assistant-2a5a3.firebaseapp.com',
    storageBucket: 'sleep-assistant-2a5a3.firebasestorage.app',
  );

}